name: my_wallet
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  google_sign_in: ^5.0.0
  flutter_facebook_login: ^3.0.0
  provider: ^4.3.3
  pie_chart: ^4.0.1
  unicorndial: ^1.1.5
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.12.0
  toast: ^0.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

  assets:
    - assets/images/