name: my_wallet
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  moor_flutter: ^3.1.0
  cupertino_icons: ^1.0.0
  provider: ^4.3.3
  unicorndial: ^1.1.5
  pie_chart: ^4.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  moor_generator: ^3.4.1
  build_runner: ^1.11.1


flutter:
  uses-material-design: true
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

  assets:
    - assets/images/
    - assets/pngs/
